require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LunchesController do

  # This should return the minimal set of attributes required to create a valid
  # Lunch. As you add validations to Lunch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "proteins" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LunchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lunches as @lunches" do
      lunch = Lunch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lunches).should eq([lunch])
    end
  end

  describe "GET show" do
    it "assigns the requested lunch as @lunch" do
      lunch = Lunch.create! valid_attributes
      get :show, {:id => lunch.to_param}, valid_session
      assigns(:lunch).should eq(lunch)
    end
  end

  describe "GET new" do
    it "assigns a new lunch as @lunch" do
      get :new, {}, valid_session
      assigns(:lunch).should be_a_new(Lunch)
    end
  end

  describe "GET edit" do
    it "assigns the requested lunch as @lunch" do
      lunch = Lunch.create! valid_attributes
      get :edit, {:id => lunch.to_param}, valid_session
      assigns(:lunch).should eq(lunch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lunch" do
        expect {
          post :create, {:lunch => valid_attributes}, valid_session
        }.to change(Lunch, :count).by(1)
      end

      it "assigns a newly created lunch as @lunch" do
        post :create, {:lunch => valid_attributes}, valid_session
        assigns(:lunch).should be_a(Lunch)
        assigns(:lunch).should be_persisted
      end

      it "redirects to the created lunch" do
        post :create, {:lunch => valid_attributes}, valid_session
        response.should redirect_to(Lunch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lunch as @lunch" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lunch.any_instance.stub(:save).and_return(false)
        post :create, {:lunch => { "proteins" => "invalid value" }}, valid_session
        assigns(:lunch).should be_a_new(Lunch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lunch.any_instance.stub(:save).and_return(false)
        post :create, {:lunch => { "proteins" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lunch" do
        lunch = Lunch.create! valid_attributes
        # Assuming there are no other lunches in the database, this
        # specifies that the Lunch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lunch.any_instance.should_receive(:update_attributes).with({ "proteins" => "MyString" })
        put :update, {:id => lunch.to_param, :lunch => { "proteins" => "MyString" }}, valid_session
      end

      it "assigns the requested lunch as @lunch" do
        lunch = Lunch.create! valid_attributes
        put :update, {:id => lunch.to_param, :lunch => valid_attributes}, valid_session
        assigns(:lunch).should eq(lunch)
      end

      it "redirects to the lunch" do
        lunch = Lunch.create! valid_attributes
        put :update, {:id => lunch.to_param, :lunch => valid_attributes}, valid_session
        response.should redirect_to(lunch)
      end
    end

    describe "with invalid params" do
      it "assigns the lunch as @lunch" do
        lunch = Lunch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lunch.any_instance.stub(:save).and_return(false)
        put :update, {:id => lunch.to_param, :lunch => { "proteins" => "invalid value" }}, valid_session
        assigns(:lunch).should eq(lunch)
      end

      it "re-renders the 'edit' template" do
        lunch = Lunch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lunch.any_instance.stub(:save).and_return(false)
        put :update, {:id => lunch.to_param, :lunch => { "proteins" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lunch" do
      lunch = Lunch.create! valid_attributes
      expect {
        delete :destroy, {:id => lunch.to_param}, valid_session
      }.to change(Lunch, :count).by(-1)
    end

    it "redirects to the lunches list" do
      lunch = Lunch.create! valid_attributes
      delete :destroy, {:id => lunch.to_param}, valid_session
      response.should redirect_to(lunches_url)
    end
  end

end
